### ISSUE TITLE
Problem: Clicking on the mathjax bookmarlet gives a html page with the word 'TRUE'.

### ISSUE THREAD

**Issue by talegari** [dzejkej/mathjax-bookmarklet#11] opened 2015-08-06 10:54 UTC
Problem: Clicking on the mathjax bookmarlet gives a html page with the word 'TRUE'.

**Comment by kubetz** [comment] 2015-08-06 17:41
Cannot reproduce this behavior. More information would be appreciated.

Are you using the most recent version from http://kubetz.github.io/mathjax-bookmarklet/ ?
If you click on the bookmarklet there, do you get the HTML page? 
What browser (& version) are you using?
Do you have javascript enabled?

**Comment by kubetz** [comment] 2015-10-18 00:40
Closing as there was no future feedback/information and I was not able to reproduce it myself.

**Closed as completed by kubetz** 2015-10-18 00:40 UTC
